# config.toml

[customizations.installer.kickstart]
contents = """

# Use the graphical installer interactive
graphical

#firstboot --enable --reconfig

network --hostname=gulpegaspe-os

# Tell Anaconda that this is a container-native bootc installation
#bootc
#ostreecontainer--url ghcr.io/gulpegaspe/gulpegaspe-os:latest

%post
sed -i '/ \/ /s/^/#/' /sysroot/etc/fstab
%end

"""
